In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('housing_sp_city.csv', encoding='latin1')

In [4]:
df.head()

,logradouro,numero,bairro,cep,cidade,tipo_imovel,area_util,banheiros,suites,quartos,vagas_garagem,anuncio_criado,tipo_anuncio,preco_venda,taxa_condominio,periodicidade,preco_aluguel,iptu_ano
0,Rua Juvenal Galeno,53,Jardim da SaÃºde,4290030.0,SÃ£o Paulo,Casa de dois andares,388.0,3.0,1.0,4.0,6.0,2017-02-07,Venda,700000,NaN,NaN,NaN,NaN
1,Rua Juruaba,16,Vila Santa Teresa (Zona Sul),4187320.0,SÃ£o Paulo,Casa,129.0,2.0,1.0,3.0,2.0,2016-03-21,Venda,336000,NaN,NaN,NaN,NaN
2,Avenida Paulista,402,Bela Vista,1311000.0,SÃ£o Paulo,Comercial,396.0,4.0,0.0,0.0,5.0,2018-12-18,LocaÃ§Ã£o,24929,4900.0,MONTHLY,29829.0,4040.0
3,Rua Alvorada,1190,Vila OlÃ­mpia,4550004.0,SÃ£o Paulo,Apartamento,80.0,2.0,1.0,3.0,2.0,2018-10-26,Venda,739643,686.0,NaN,NaN,1610.0
4,Rua Curitiba,380,ParaÃ­so,4005030.0,SÃ£o Paulo,Apartamento,3322.0,5.0,4.0,4.0,5.0,2018-12-14,Venda,7520099,6230.0,NaN,NaN,18900.0

In [5]:
df.describe(include='object')

,logradouro,numero,bairro,cidade,tipo_imovel,anuncio_criado,tipo_anuncio,periodicidade
count,126962,89823,133943,133964,133964,133964,133964,29051
unique,13017,3356,1780,174,18,1815,2,3
top,Rua Bela Cintra,1,Jardim Paulista,SÃ£o Paulo,Apartamento,2017-04-13,Venda,MONTHLY
freq,834,1261,4284,133456,72241,3217,105332,29029

In [6]:
df['tipo_anuncio'].unique()

array(['Venda', 'LocaÃ§Ã£o'], dtype=object)

In [7]:
df = df[ df['tipo_anuncio'] == 'LocaÃ§Ã£o']

In [8]:
df.drop(columns=['logradouro', 'numero', 'tipo_anuncio'], inplace=True)

In [9]:
df.head()

,bairro,cep,cidade,tipo_imovel,area_util,banheiros,suites,quartos,vagas_garagem,anuncio_criado,preco_venda,taxa_condominio,periodicidade,preco_aluguel,iptu_ano
2,Bela Vista,1311000.0,SÃ£o Paulo,Comercial,396.0,4.0,0.0,0.0,5.0,2018-12-18,24929,4900.0,MONTHLY,29829.0,4040.0
5,Vila Uberabinha,4514032.0,SÃ£o Paulo,Flat,45.0,0.0,1.0,1.0,1.0,2018-10-09,1889,560.0,MONTHLY,2450.0,87.0
18,Cidade MonÃ§Ãµes,4560000.0,SÃ£o Paulo,Loja,126.0,4.0,0.0,4.0,2.0,2018-07-02,3849,0.0,MONTHLY,3849.0,3311.0
20,Vila Pompeia,5020000.0,SÃ£o Paulo,CondomÃ­nio,274.0,3.0,0.0,0.0,2.0,2018-08-02,7699,0.0,MONTHLY,7699.0,0.0
39,Jardim Guedala,5612001.0,SÃ£o Paulo,Casa,480.0,6.0,3.0,0.0,4.0,2018-09-07,7000,0.0,MONTHLY,7000.0,0.0

In [10]:
df.describe()

,cep,area_util,banheiros,suites,quartos,vagas_garagem,preco_venda,taxa_condominio,preco_aluguel,iptu_ano
count,2.738200e+04,28105.000000,28387.000000,24720.000000,26892.000000,27172.000000,2.863200e+04,2.581200e+04,2.861900e+04,2.702500e+04
mean,3.452006e+06,323.770254,2.330785,0.807565,1.473412,3.532349,9.602494e+03,1.610510e+03,1.105842e+04,1.443734e+04
std,2.509272e+06,1145.946875,2.658092,1.166359,1.713303,10.069788,7.495025e+04,1.627098e+04,7.713733e+04,1.748524e+06
min,0.000000e+00,1.000000,0.000000,0.000000,0.000000,0.000000,7.000000e+01,0.000000e+00,7.000000e+01,0.000000e+00
25%,1.424002e+06,48.000000,1.000000,0.000000,0.000000,1.000000,1.750000e+03,0.000000e+00,2.310000e+03,7.000000e+01
50%,4.006052e+06,130.000000,2.000000,0.000000,1.000000,2.000000,3.423000e+03,7.590000e+02,4.130000e+03,1.820000e+02
75%,4.567003e+06,287.000000,3.000000,1.000000,3.000000,4.000000,8.049000e+03,1.386000e+03,9.170000e+03,7.000000e+02
max,9.981030e+07,74211.000000,99.000000,19.000000,100.000000,589.000000,1.190000e+07,1.735300e+06,1.190000e+07,2.830242e+08

In [11]:
df.describe(include='object')

                 bairro      cidade  tipo_imovel anuncio_criado periodicidade
count             28626       28632        28632          28632         28632
unique              907          68           18           1296             3
top     Jardim Paulista  SÃ£o Paulo  Apartamento     2018-06-21       MONTHLY
freq               2053       28510         8095            713         28610

In [12]:
df.isna().sum()

bairro                6
cep                1250
cidade                0
tipo_imovel           0
area_util           527
banheiros           245
suites             3912
quartos            1740
vagas_garagem      1460
anuncio_criado        0
preco_venda           0
taxa_condominio    2820
periodicidade         0
preco_aluguel        13
iptu_ano           1607
dtype: int64

In [13]:
df.dropna(inplace=True)

In [14]:
df.head()

,bairro,cep,cidade,tipo_imovel,area_util,banheiros,suites,quartos,vagas_garagem,anuncio_criado,preco_venda,taxa_condominio,periodicidade,preco_aluguel,iptu_ano
2,Bela Vista,1311000.0,SÃ£o Paulo,Comercial,396.0,4.0,0.0,0.0,5.0,2018-12-18,24929,4900.0,MONTHLY,29829.0,4040.0
5,Vila Uberabinha,4514032.0,SÃ£o Paulo,Flat,45.0,0.0,1.0,1.0,1.0,2018-10-09,1889,560.0,MONTHLY,2450.0,87.0
18,Cidade MonÃ§Ãµes,4560000.0,SÃ£o Paulo,Loja,126.0,4.0,0.0,4.0,2.0,2018-07-02,3849,0.0,MONTHLY,3849.0,3311.0
20,Vila Pompeia,5020000.0,SÃ£o Paulo,CondomÃ­nio,274.0,3.0,0.0,0.0,2.0,2018-08-02,7699,0.0,MONTHLY,7699.0,0.0
39,Jardim Guedala,5612001.0,SÃ£o Paulo,Casa,480.0,6.0,3.0,0.0,4.0,2018-09-07,7000,0.0,MONTHLY,7000.0,0.0

In [15]:
df.dtypes

bairro              object
cep                float64
cidade              object
tipo_imovel         object
area_util          float64
banheiros          float64
suites             float64
quartos            float64
vagas_garagem      float64
anuncio_criado      object
preco_venda          int64
taxa_condominio    float64
periodicidade       object
preco_aluguel      float64
iptu_ano           float64
dtype: object

In [16]:
df.head()

,bairro,cep,cidade,tipo_imovel,area_util,banheiros,suites,quartos,vagas_garagem,anuncio_criado,preco_venda,taxa_condominio,periodicidade,preco_aluguel,iptu_ano
2,Bela Vista,1311000.0,SÃ£o Paulo,Comercial,396.0,4.0,0.0,0.0,5.0,2018-12-18,24929,4900.0,MONTHLY,29829.0,4040.0
5,Vila Uberabinha,4514032.0,SÃ£o Paulo,Flat,45.0,0.0,1.0,1.0,1.0,2018-10-09,1889,560.0,MONTHLY,2450.0,87.0
18,Cidade MonÃ§Ãµes,4560000.0,SÃ£o Paulo,Loja,126.0,4.0,0.0,4.0,2.0,2018-07-02,3849,0.0,MONTHLY,3849.0,3311.0
20,Vila Pompeia,5020000.0,SÃ£o Paulo,CondomÃ­nio,274.0,3.0,0.0,0.0,2.0,2018-08-02,7699,0.0,MONTHLY,7699.0,0.0
39,Jardim Guedala,5612001.0,SÃ£o Paulo,Casa,480.0,6.0,3.0,0.0,4.0,2018-09-07,7000,0.0,MONTHLY,7000.0,0.0

In [17]:
X = df.drop(columns=['preco_aluguel'])
y = df['preco_aluguel']

In [18]:
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(include=['int', 'float']).columns

In [19]:
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

In [20]:
# ENCONDING DAS COLUNAS CATEGORICAS - Label encoder

In [21]:
# NORMALIZAÇAO DAS COLUNAS NUMERICAS

In [22]:
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1), categorical_cols),
        ("num", StandardScaler(), numerical_cols)
    ]
)

In [23]:
from sklearn.pipeline import Pipeline
from xgboost import XGBRegressor

In [24]:
model = XGBRegressor(random_state=42)

pipeline = Pipeline(steps=[('preprocessor', preprocessor),
                           ('regressor', model)])

In [25]:
pipeline.fit(X,y)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  Index(['bairro', 'cidade', 'tipo_imovel', 'anuncio_criado', 'periodicidade'], dtype='object')),
                                                 ('num', StandardScaler(),
                                                  Index(['cep', 'area_util', 'banheiros', 'suites', 'quartos', 'vagas_garagem',
       'preco_venda', 'taxa_condo...
                              feature_types=None, feature_weights=None,
                              gamma=None, grow_policy=None,
                              importance_type=None,
                              interaction_constraints=None, learning_rate=None,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=None, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, multi_strategy=None,
                              n_estimators=None, n_jobs=None,
                              num_parallel_tree=None, ...))])

In [26]:
import pickle

# Save the pipeline to a pickle file
with open('model.pkl', 'wb') as f:
    pickle.dump(pipeline, f)

print("Pipeline saved successfully as housing_price_prediction_pipeline.pkl")

Pipeline saved successfully as housing_price_prediction_pipeline.pkl

In [27]:
X.sample(1)

,bairro,cep,cidade,tipo_imovel,area_util,banheiros,suites,quartos,vagas_garagem,anuncio_criado,preco_venda,taxa_condominio,periodicidade,iptu_ano
103434,Santana,2401000.0,SÃ£o Paulo,EscritÃ³rio,47.0,1.0,0.0,0.0,1.0,2019-01-08,1120,389.0,MONTHLY,137.0

In [28]:
pipeline.predict(X.sample(1))

array([3907.6536], dtype=float32)

In [30]:
import json

# Sample one row from the DataFrame X
sample_row = X.sample(1)

# Convert the sampled row to a JSON object
sample_json = sample_row.to_json(orient='records')

# Print the JSON object
print(sample_json)

[{"bairro":"Vila Suzana","cep":5630070.0,"cidade":"S\u00c3\u00a3o Paulo","tipo_imovel":"Apartamento","area_util":70.0,"banheiros":2.0,"suites":1.0,"quartos":2.0,"vagas_garagem":2.0,"anuncio_criado":"2019-02-20","preco_venda":1540,"taxa_condominio":595.0,"periodicidade":"MONTHLY","iptu_ano":125.0}]