In [23]:
import statistics as sts
import pandas as pd

In [ ]:
print("Hello")

Hello

In [15]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

In [21]:
statistics.mode(lista)

14

# MÉDIA, MEDIANA e MODA // Statistics

In [16]:
sts.mean(lista)

15.466666666666667

In [17]:
sts.median(lista)

15.0

In [19]:
sts.mode(lista)

14

# MÉDIA, MEDIANA e MODA // Pandas

In [24]:
df = pd.DataFrame(lista)

In [25]:
type(df)

pandas.core.frame.DataFrame

In [26]:
type(lista)

list

In [27]:
df.mean()

0    15.466667
dtype: float64

In [28]:
df.mode()

    0
0  14

In [29]:
df.median()

0    15.0
dtype: float64

# VARIANCIA E DESVIO PADRÃO // Pandas

In [30]:
df.std()

0    8.807259
dtype: float64

In [31]:
variancia = df.std() ** 2

In [32]:
print(variancia)

0    77.567816
dtype: float64

# VARIANCIA E DESVIO PADRÃO // Statistics

In [34]:
sts.variance(lista)

77.56781609195403

In [35]:
sts.stdev(lista)

8.807259283792774